### ISSUE TITLE
node not found.

### ISSUE THREAD

**Issue by rakshans1** [unlight/sublime-import-helper#43]
Node command not found error when using nvm.

**Comment by unlight** [comment]
What is your OS?
What version of nvm?
Can you run node from any place of file system (means is node binary in your path environment)?

**Comment by rakshans1** [comment]
Os: Ubuntu 16.04
Nvm: 0.33.2

Yes node is loaded in environment path

**Comment by RickMeijer** [comment]
Same issue.
Os: MacOS 10.12.6
NVM: 0.33.2

Not finding a node executable in sublime is a common issue, apparently. See https://github.com/victorporof/Sublime-HTMLPrettify#oh-noez-command-not-found, for example.
It has to do whether your nvm script is in your profile or rc, whether sublime was run from the terminal or outside of one. Specifying a node_path in your sublime settings helps with some plugins, but for me **the (temporary) fix was to add the correct dir to the "paths" setting in sublime text**. I'm not getting any imports from the node_modules dir though, but I'm not sure if that's by design.
Hope this helps.

**Comment by unlight** [comment]
@RickMeijer
Thanks, I thought about it.
Guys from stack overflow telling that: `shell=True` will solve the issue.
Do you know is that true?

**Comment by unlight** [comment]
Possible fixed in v1.7.0

**Comment by unlight** [comment]
@RickMeijer 
@rakshans1 
Please, check version 1.7.0

**Comment by woozie** [comment]
same

<img width="638" alt="screen shot 2017-11-27 at 21 54 53" src="https://user-images.githubusercontent.com/3217527/33286301-ab7a0cee-d3bd-11e7-8aa4-66b7baf9781d.png">

**Comment by unlight** [comment]
In v1.7.3 introduced `node_bin` setting: https://github.com/unlight/sublime-import-helper#node_bin
It should solve the issue.

**Comment by woozie** [comment]
![screen shot 2017-11-29 at 16 23 02](https://user-images.githubusercontent.com/3217527/33379779-ab72486e-d521-11e7-825a-e7ba39e55a5e.png)

**Comment by unlight** [comment]
@woozie
Thanks for quick response.
I see NODE_BIN is equal to `'node'` (default value), so I got some questions:
1. Are you sure that you are using version 1.7.3 (you can check it in `Sublime-Text-3/Data/Packages/ImportHelper/package.json -> version`)
2. Did you specified `node_bin` setting? If yes. In which file: project data file, import helper user settings or user preferences?

**Comment by woozie** [comment]
After clean install works properly. It was a package control cache.

Can you use super key binding instead ctrl? A lot of users running on mac

**Comment by unlight** [comment]
@woozie 
You can rebind keybindins as you wish.
Top menu -> Preference -> Key Bindings:
```
[
    {
        "keys": ["super+alt+i"],
        "command": "insert_import",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "source.ts, source.tsx, source.js, source.jsx" }
        ]
    },
    {
        "keys": ["alt+i", "alt+l"],
        "command": "list_imports",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "source.ts, source.tsx, source.js, source.jsx" }
        ]
    },
    {
        "keys": ["alt+i", "alt+k"],
        "command": "import_from_clipboard",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "source.ts, source.tsx, source.js, source.jsx" }
        ]
    },
    {
        "keys": ["alt+i", "alt+u"],
        "command": "remove_unused",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "source.ts, source.tsx, source.js, source.jsx" }
        ]
    }
]
```

**Comment by unlight** [comment]
@RickMeijer 
@rakshans1 
Guys can you confirm that new version works for you?
And how (did you specified node_bin setting)?

**Comment by RickMeijer** [comment]
I'm so sorry for not replying. Work got in the way. 
For me the solution was as I said in my last post (adding node bin directory to my paths in sublime). Since I never got the error after making node available to import helper, I kinda glossed over this discussion.
Thanks for your time! It all seems to work for me.
