### ISSUE TITLE
Sorting named imports

### ISSUE THREAD

**Issue by kapooostin** [unlight/sublime-import-helper#48]
Thank you for this very handy plugin.

Is it possible to an option to automatically sort named imports (I mean, names inside curly brackets)?

**Comment by unlight** [comment]
Hi. Why existing options are not suitable for you?
1. [tslint/ordered-imports](https://palantir.github.io/tslint/rules/ordered-imports/)
2. [eslint/sort-imports](https://eslint.org/docs/rules/sort-imports)
3. https://github.com/AlexJuarez/eslint-plugin-import-order-autofix

Btw, similar issues in prettier https://github.com/prettier/prettier/issues/949 was closed due to out of scope.

**Comment by unlight** [comment]
Oh, I got your point, You want to insert expression to specific positions to prevent tslint/eslint complains and using manual/semi/auto sorting.

**Comment by kapooostin** [comment]
Well, I actually never knew about the options above and sorted multiple import members by hand.

1. I do not use Typescript, so to use this option would mean too much trouble for me. However TSLint possibilities look very promising.

2. I do use ESLint, but I do not need to group my imports the way it suggests and I don't see an option to disable it. The only thing I want to get here is member sorting.

3. Well, it offers ordering of all imports, not members of a single import. And it has an open issue about loosing some imports after processing.

Prettier avoids changing AST, so it is only fair to opt out of requests like ordering or joining imports. But your plugin does modify AST, that's why I guessed it would be possible to sort members on the fly.
